name: Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.syrinegh }}
          password: ${{ secrets.GITHUB_TOKEN }}
          regisrty: docker.pkg.github.com
          repository: ${{ github.repository }}/next
          tags: latest, ${{ github.run_number }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: syrinegh/next
          tags: latest, ${{ github.run_number }}
