name: Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.syrinegh }}
          password: ${{ secrets.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 }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: syrinegh/cooldesyrine:latest
